project:
  type: website

website:
  title: "A Place for My Thoughts"
  navbar:
    right:
      - about.qmd
  page-footer: "Copyright 2024, CY LI" 
format:
  html:
    theme: journal
    css: styles.css
execute:
  freeze: auto



